--- #YAML:1.0
name:                CSS-Prepare
version:             v0.9.2
abstract:            ~
license:             ~
author:              
    - Mark Norman Francis <norm@cackhanded.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Digest::SHA1:                  0
    Modern::Perl:                  0
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
